blank_issues_enabled: false
contact_links:
  - name: Q&A / Usage questions
    url: https://github.com/NestorDP/cppserial/discussions
    about: Ask and answer questions, share tips, and propose ideas.
  - name: Documentation
    url: https://github.com/NestorDP/cppserial#readme
    about: Read setup and usage instructions.
